### ISSUE TITLE
Chaining commands failing.

### ISSUE THREAD

**Issue by kiksen1987** [MCluck90/simple-ssh#51]
Tried the code example on the front page:
```javascript
ssh
    .exec('echo "Node.js"', {
        out: console.log.bind(console)
    })
    .exec('echo "is"', {
        out: console.log.bind(console)
    })
    .exec('echo "awesome!"', {
        out: console.log.bind(console)
    })
    .start();
```

which only resulted in:

Node.js

is

**Comment by MCluck90** [comment]
Hi! I'm not really actively working on this anymore so that's why it took so long to reply. I hate to say "it works on my machine" but... well, you get the point. I would need more information about your operating machine, where you're connecting to, etc. to even begin to guess at what's going wrong.

**Comment by kiksen1987** [comment]
I was working from local windows 10 machine.
Connection to AWS machine.
My init. use case was:
Startup new AWS machine.
Install dependencies using simple ssh.
Start app.

But somehow the last command never worked.
Tried to add extra dummy command and everything worked.

It's just a sideproject, so no worries :)

**Comment by CakeIsntLying** [comment]
Ok I fixed the module's bug by changing the 
`  stream.on('exit', function(code) {`
in the module code into : 
`  stream.on('end', function(code) {`
The problem is the exit event firing before the data event and ending the process too early, this fix should work because the end event fires after the data event.
I haven't tested this extensively so use at your own risks.

**Comment by sean3z** [comment]
I can confirm I'm having the same issue but https://github.com/CakeIsntLying/simple-ssh/commit/d7bdd27d39d79eac1bce32655433a3dcab7beaf2 unfortunately did not fix it for me
